### ISSUE TITLE
Release fluxfinder 1.0.0

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/fluxfinder#76]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Add our paper coauthors as package 'ctb' 
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ] `usethis::use_news_md()`

**Comment by wilsonsj100** [comment]
Ran devtools::check(remote = TRUE, manual = TRUE) - We have one note about DOIs I think 

 R CMD check results ─────────────────────────────────────────────────────── fluxfinder 0.1.0 ────
Duration: 2m 4.9s

❯ checking CRAN incoming feasibility ... [78s] NOTE
  Maintainer: 'Stephanie Wilson <wilsonsj@si.edu>'
  
  New submission
  
  Found the following URLs which should use \doi (with the DOI name only):
    File 'ffi_fit_models.Rd':
      http://dx.doi.org/10.1016/j.soilbio.2003.07.005
      http://dx.doi.org/10.2136/sssaj1981.03615995004500020017x
    File 'ffi_hm1981.Rd':
      http://dx.doi.org/10.2136/sssaj1981.03615995004500020017x
    File 'ideal-gas-law.Rd':
      http://dx.doi.org/10.1016/S0168-1923(02)00023-0

0 errors ✔ | 0 warnings ✔ | 1 note ✖

**Comment by bpbond** [comment]
OK! Thanks. Do you know how to fix?

**Comment by bpbond** [comment]
Here's an example: https://github.com/dankelley/oce/issues/1770#issuecomment-754615072

**Comment by wilsonsj100** [comment]
Thank you for the example - I am going to try... make a new branch, edit the doi's, then pushing up back up to Github

**Comment by bpbond** [comment]
New branch
Edit DOIs
Rebuild the documentation
Commit and push

**Comment by wilsonsj100** [comment]
Okay - let's see how I did. I requested your review.

**Comment by wilsonsj100** [comment]
After DOI fixes... reran and only note is that this is a new submission so check!

── R CMD check results ─────────────────────────────────────────────────────── fluxfinder 0.1.0 ────
Duration: 2m 1.5s

❯ checking CRAN incoming feasibility ... [76s] NOTE
  Maintainer: 'Stephanie Wilson <wilsonsj@si.edu>'
  
  New submission

0 errors ✔ | 0 warnings ✔ | 1 note ✖

**Comment by bpbond** [comment]
Woo hoo!!! 🙌

**Comment by wilsonsj100** [comment]
@bpbond are we good on the pull and push if all the checks went through after my last PR and merge? If so, then I think I can proceed with cran submission steps?

**Comment by wilsonsj100** [comment]
FYI: We got some feedback from CRAN and there are a few things to do then resubmit....

If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year, ISBN:...)
or if those are not available: <[https:...]https:...>
with no space after 'doi:', 'https:' and angle brackets for
auto-linking. (If you want to add a title as well please put it in
quotes: "Title")

\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user. Does not seem necessary.
Please replace \dontrun with \donttest.

Please unwrap the examples if they are executable in < 5 sec, or replace
dontrun{} with \donttest{}.

Please fix and resubmit.

**Comment by bpbond** [comment]
Okay! Those seem straightforward.

**Comment by wilsonsj100** [comment]
Published on CRAN :) Woohoo! 

https://cran.r-project.org/package=fluxfinder
